name: Say Hi!
description: Say hi and save time
author: Heidi

inputs: 
  who-to-greet:
    required: true
    default: 'world'
outputs:
  time:
    description: 'The time we greeted you'


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}  
