name: Reuse other workflow

on:
  - workflow_dispatch

jobs:
  call-workflow:
    uses: ./.github/reusable.yml@main
    with:
      who-to-greet: '@octocat'

  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
